### ISSUE TITLE
hosting; when, where and how?

### ISSUE THREAD

**Issue by serundeputy** [Backdrop4Good/blm2020#2]
@laryn Does BLM 2020 have budget or existing hosting that we are working with?

If not; Let's reach out to some hosting providers to see if they will help with hosting:

- ~~[ ] Pantheon~~
- ~~[ ] Platform.sh~~

**Comment by laryn** [comment]
@serundeputy No, nothing to start with/work with at the moment. Let's reach out and see what these say. Do you have contacts at either/both?

**Comment by serundeputy** [comment]
@laryn good to know! thanks.

Yes I'll reach out and report back.

**Comment by laryn** [comment]
My org is willing to host the site. Per our PMs @serundeputy let me know if you have all you need to do the initial config/setup.

**Comment by serundeputy** [comment]
- [x] i can ssh in
- [ ] i can login to the cpanel
- [x] i can see `staging` and `production` under `public_html` 
  - [ ] presumeably this is where the `vhosts` (domains) are pointed?
  - [ ] I don't see how to configure the `vhosts` and the ssh account does not have access to `/etc/apache` to do any config via command line.
  - [ ] i need the `vhosts` to point to `staging/web` and `production/web`

**Comment by laryn** [comment]
@serundeputy I marked off the last three sub-items as I think they are complete now.
